name: ReVanced Test Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Download APKs from APKMirror
        run: ./download_apkmirror.sh

      - name: Test Build APKs
        run: |
          ./build_revanced.sh
          for filename in build/rvx-root-hybrid.apk build/rvx-nonroot-hybrid.apk build/rvx-root-material.apk build/rvx-nonroot-material.apk build/rvx-root-amoled.apk build/rvx-nonroot-amoled.apk build/rvx-music-root.apk build/rvx-music-nonroot.apk; do
            if [ -e "$filename" ]; then
              printf '"%s" exists\n' "$filename"
            else
              echo "APK build failed"
              exit 1
            fi
          done
          rm -rf build
